#!/bin/bash
set +x

# Install homebrew if it doesn't exist
which -s brew || /usr/bin/ruby -e "$(curl -fsSkL raw.github.com/mxcl/homebrew/go)"

# Make sure we’re using the latest Homebrew
brew update

# Upgrade any already-installed formulae
brew upgrade

# Install GNU core utilities (those that come with OS X are outdated)
brew install coreutils
echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
brew install findutils
# Install Bash 4
brew install bash

# Install wget with IRI support
brew install wget --enable-iri

# Install more recent versions of some OS X tools
brew tap homebrew/dupes
brew install homebrew/dupes/grep

# Install everything else
brew install ack
brew install apple-gcc42
brew install elasticsearch
brew install exiv2
brew install freetype
brew install gecode
brew install git
brew install graphiz
brew install hub
brew install imagemagick
brew install lynx
brew install memcached
brew install mongodb
brew install mysql
brew install ngrep
brew install node
brew install postgresql
brew install rabbitmq
brew install redis
brew install rename
brew install rhino
brew install riak
brew install solr
brew install sphinx
brew install sqlite
brew install tcpdump
brew install tree
brew install webkit2png

# Remove outdated versions from the cellar
brew cleanup
